name = "hax"
version = "0.1.0"
defaultTargets = ["Hax", "CoreModels"]

[[lean_lib]]
name = "Hax"

[[lean_lib]]
name = "CoreModels"

[[require]]
name = "aeneas"
git = { url = "https://github.com/cryspen/aeneas", subDir = "backends/lean" }
rev = "9f5df8bfdc0f1c14d885656906d9d49f8bc7dde3"
