-- [chacha20]: external functions.
--
-- Hand-written Lean models for constructs the aeneas/CoreModels lean backend
-- does not (yet) model but that chacha20 relies on:
--   * `hax_bounded_integers::BoundedUsize` (the `StateIdx` refinement type),
--     its `into_checked` constructor and its `Index`/`IndexMut` instances,
--   * mutable array indexing (`core::ops::IndexMut` for `[T; N]`),
--   * `core::result::Result::unwrap`,
--   * `hax_lib::assume!` (`hax_lib.assume` + `Prop::from::<bool>`).
--
-- The models are faithful for panic-freedom: the only operations that can
-- fail (`Slice.index_usize`, `into_checked`, `Result.unwrap`) fail exactly
-- when the corresponding Rust operation panics; the write-back setters are
-- total and `assume` is a no-op.
import Aeneas
import CoreModels
import Chacha20.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.nameCheck false

set_option maxHeartbeats 1000000
set_option maxRecDepth 2048

namespace CoreModels

/-! ## Additions to the `core` model -/
namespace core

/-- `core::ops::IndexMut`: like `Index`, but also returns a write-back closure. -/
structure ops.index.IndexMut (Self : Type) (Idx : Type) (Self_Output : Type) where
  index_mut : Self → Idx → Aeneas.Std.Result (Self_Output × (Self_Output → Self))

/-- `IndexMut<I> for [T; N]`, delegating to the slice `IndexMut<I>` instance. -/
def Array.Insts.CoreOpsIndexIndexMut.index_mut
    {T I Self_Output : Type} {N : Std.Usize}
    (inst : ops.index.IndexMut (Slice T) I Self_Output)
    (self : Array T N) (i : I) :
    Aeneas.Std.Result (Self_Output × (Self_Output → Array T N)) := do
  let (x, back) ← inst.index_mut (Array.to_slice self) i
  ok (x, fun v => Array.from_slice self (back v))

/-- `Debug` instance for `TryFromSliceError` (needed by `Result::unwrap`). -/
def array.TryFromSliceError.Insts.CoreFmtDebug : fmt.Debug array.TryFromSliceError :=
  fmt.Debug.Blanket array.TryFromSliceError

/-- `Result<T, E>::unwrap` (requires `E : Debug`): panics on `Err`. -/
def result.Result.unwrap {T E : Type} (_debug : fmt.Debug E) (self : result.Result T E) :
    Aeneas.Std.Result T :=
  match self with
  | .Ok v => Aeneas.Std.Result.ok v
  | .Err _ => panicking.internal.panic T

end core

/-! ## `hax_bounded_integers::BoundedUsize` -/
namespace hax_bounded_integers

/-- A `usize` refined to the range `[lo, hi]`. -/
structure hax__autogenerated_refinement__BoundedUsize.BoundedUsize
    (lo hi : Std.Usize) where
  val : Std.Usize
  hlo : lo.val ≤ val.val
  hhi : val.val ≤ hi.val

/-- `usize::into_checked::<BoundedUsize<lo, hi>>`: succeeds iff `lo ≤ x ≤ hi`. -/
def Usize.Insts.Hax_libRefineAsBoundedUsize.into_checked
    (lo hi x : Std.Usize) :
    Result (hax__autogenerated_refinement__BoundedUsize.BoundedUsize lo hi) :=
  if h : lo.val ≤ x.val ∧ x.val ≤ hi.val then
    .ok ⟨x, h.1, h.2⟩
  else
    .fail .panic

/-- `Index<BoundedUsize> for [T]`: read the element at the (in-range) index. -/
def Slice.Insts.CoreOpsIndexIndexBoundedUsizeT (T : Type) (lo hi : Std.Usize) :
    core.ops.index.Index (Slice T)
      (hax__autogenerated_refinement__BoundedUsize.BoundedUsize lo hi) T := {
  index := fun s a => Slice.index_usize s a.val
}

/-- `IndexMut<BoundedUsize> for [T]`: read + total write-back at the index. -/
def Slice.Insts.CoreOpsIndexIndexMutBoundedUsizeT (T : Type) (lo hi : Std.Usize) :
    core.ops.index.IndexMut (Slice T)
      (hax__autogenerated_refinement__BoundedUsize.BoundedUsize lo hi) T := {
  index_mut := fun s a => do
    let x ← Slice.index_usize s a.val
    ok (x, fun v => Slice.set s a.val v)
}

end hax_bounded_integers

/-! ## `hax_lib::assume!` -/
namespace hax_lib

/-- `hax_lib::Prop` is modelled by Lean's `Prop`. -/
abbrev prop.Prop : Type := Prop

/-- `<Prop as From<bool>>::from`. -/
def prop.Prop.Insts.CoreConvertFromBool.from (p : Prop) : Result prop.Prop :=
  ok p

/-- `hax_lib::assume!`: a no-op at runtime, hence panic-free. -/
def assume (_p : prop.Prop) : Result Unit :=
  ok ()

end hax_lib

end CoreModels
