-- [chacha20]: external functions.
--
-- Hand-written Lean models for constructs the aeneas/CoreModels lean backend
-- does not (yet) model but that chacha20 relies on:
--   * `hax_bounded_integers::BoundedUsize` (the `StateIdx` refinement type),
--     its `into_checked` constructor and its `Index`/`IndexMut` instances,
--   * mutable array indexing (`core::ops::IndexMut` for `[T; N]`),
--   * `core::result::Result::unwrap`,
--   * `hax_lib::assume!` (`hax_lib.assume` + `Prop::from::<bool>`).
--
-- The models are faithful for panic-freedom: the only operations that can
-- fail (`Slice.index_usize`, `into_checked`, `Result.unwrap`) fail exactly
-- when the corresponding Rust operation panics; the write-back setters are
-- total and `assume` is a no-op.
import Aeneas
import CoreModels
import Hax
import Chacha20.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
open Std.Tactic
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.nameCheck false

set_option maxHeartbeats 1000000
set_option maxRecDepth 2048

namespace CoreModels

/-! ## Additions to the `core` model -/
namespace core

/-- `core::ops::IndexMut`: like `Index`, but also returns a write-back closure. -/
structure ops.index.IndexMut (Self : Type) (Idx : Type) (Self_Output : Type) where
  index_mut : Self → Idx → Aeneas.Std.Result (Self_Output × (Self_Output → Self))

/-- `IndexMut<I> for [T; N]`, delegating to the slice `IndexMut<I>` instance. -/
def Array.Insts.CoreOpsIndexIndexMut.index_mut
    {T I Self_Output : Type} {N : Std.Usize}
    (inst : ops.index.IndexMut (Slice T) I Self_Output)
    (self : Array T N) (i : I) :
    Aeneas.Std.Result (Self_Output × (Self_Output → Array T N)) := do
  let (x, back) ← inst.index_mut (Array.to_slice self) i
  ok (x, fun v => Array.from_slice self (back v))

/-- `Debug` instance for `TryFromSliceError` (needed by `Result::unwrap`). -/
def array.TryFromSliceError.Insts.CoreFmtDebug : fmt.Debug array.TryFromSliceError :=
  fmt.Debug.Blanket array.TryFromSliceError

/-- `Result<T, E>::unwrap` (requires `E : Debug`): panics on `Err`. -/
def result.Result.unwrap {T E : Type} (_debug : fmt.Debug E) (self : result.Result T E) :
    Aeneas.Std.Result T :=
  match self with
  | .Ok v => Aeneas.Std.Result.ok v
  | .Err _ => panicking.internal.panic T

end core

/-! ## `hax_bounded_integers::BoundedUsize` -/
namespace hax_bounded_integers

/-- A `usize` refined to the range `[lo, hi]`. -/
structure hax__autogenerated_refinement__BoundedUsize.BoundedUsize
    (lo hi : Std.Usize) where
  val : Std.Usize
  hlo : lo.val ≤ val.val
  hhi : val.val ≤ hi.val

/-- `usize::into_checked::<BoundedUsize<lo, hi>>`: succeeds iff `lo ≤ x ≤ hi`. -/
def Usize.Insts.Hax_libRefineAsBoundedUsize.into_checked
    (lo hi x : Std.Usize) :
    Result (hax__autogenerated_refinement__BoundedUsize.BoundedUsize lo hi) :=
  if h : lo.val ≤ x.val ∧ x.val ≤ hi.val then
    .ok ⟨x, h.1, h.2⟩
  else
    .fail .panic

/-- `Index<BoundedUsize> for [T]`: read the element at the (in-range) index. -/
def Slice.Insts.CoreOpsIndexIndexBoundedUsizeT (T : Type) (lo hi : Std.Usize) :
    core.ops.index.Index (Slice T)
      (hax__autogenerated_refinement__BoundedUsize.BoundedUsize lo hi) T := {
  index := fun s a => Slice.index_usize s a.val
}

/-- `IndexMut<BoundedUsize> for [T]`: read + total write-back at the index. -/
def Slice.Insts.CoreOpsIndexIndexMutBoundedUsizeT (T : Type) (lo hi : Std.Usize) :
    core.ops.index.IndexMut (Slice T)
      (hax__autogenerated_refinement__BoundedUsize.BoundedUsize lo hi) T := {
  index_mut := fun s a => do
    let x ← Slice.index_usize s a.val
    ok (x, fun v => Slice.set s a.val v)
}

end hax_bounded_integers

/-! ## `hax_lib::assume!` -/
namespace hax_lib

/-- `hax_lib::Prop` is modelled by Lean's `Prop`. -/
abbrev prop.Prop : Type := Prop

/-- `<Prop as From<bool>>::from`. -/
def prop.Prop.Insts.CoreConvertFromBool.from (p : Prop) : Result prop.Prop :=
  ok p

/-- `hax_lib::assume!`: a no-op at runtime, hence panic-free. -/
def assume (_p : prop.Prop) : Result Unit :=
  ok ()

end hax_lib

end CoreModels

/-! ## Loop-over-range machinery (copied from the loop_equivalence example)

Provides the `@[spec] forLoopWithInvariant_spec` lemma that lets `hax_mvcgen`
discharge `for i in s..e` loops (over `Usize`) after `for_loop_with_invariant`. -/

/-! ## Iterator spec -/

@[spec]
theorem IteratorRange_next_spec (i e : Usize) {Q}
    (h_lt : (h : i.val < e.val) →
      ∀ (s : Usize), s.val = i.val + 1 →
        (Q.1 (some i, { start := s, «end» := e })).down)
    (h_ge : i.val ≥ e.val →
      (Q.1 (none, { start := i, «end» := e })).down) :
    ⦃ ⌜ True ⌝ ⦄
    core.IteratorRange.next core.Usize.Insts.CoreIterRangeStep
      { start := i, «end» := e }
    ⦃ Q ⦄ := by
  unfold core.IteratorRange.next core.Usize.Insts.CoreIterRangeStep
  by_cases h : i.val < e.val
  · -- i < e: partial_cmp returns Less, forward_checked succeeds.
    have h_lt' := h_lt h
    simp_all [compare, compareOfLessAndEq,
      core.Usize.Insts.CoreCmpPartialOrdUsize, core.mkUPartialOrd,
      core.Usize.Insts.CoreCloneClone.clone]
    -- `forward_checked` produces `some s` with `s.val = i.val + 1`.
    have hbnd : i.val + (1#usize).val ≤ Usize.max := by scalar_tac
    have hno_ovf := UScalar.overflowing_add_eq i (1#usize)
    have hi1_le : ¬ (i.val + (1#usize).val > UScalar.max .Usize) := by scalar_tac
    simp only [hi1_le, if_false] at hno_ovf
    obtain ⟨hsv, hovf⟩ := hno_ovf
    simp only [core.Usize.Insts.CoreIterRangeStep.forward_checked,
      core.convert.TryFromUTInfallible.Blanket.try_from,
      core.convert.From.Blanket.from,
      core.num.Usize.checked_add, core.num.Usize.overflowing_add,
      rust_primitives.arithmetic.overflowing_add_usize]
    mvcgen
    generalize hov : UScalar.overflowing_add i (1#usize) = ov at *
    obtain ⟨result, overflowed⟩ := ov
    subst hovf
    exact h_lt' _ (by simpa using hsv)
  · -- i ≥ e: partial_cmp returns Equal or Greater (not Less).
    have hle := Nat.le_of_not_lt h
    have h_ge' := h_ge hle
    simp_all [compare, compareOfLessAndEq,
      core.Usize.Insts.CoreCmpPartialOrdUsize, core.mkUPartialOrd]
    mvcgen
    all_goals first
      | exact h_ge'
      | (rename_i hlt
         split at hlt <;> rename_i heq <;> split at heq <;>
           (try simp_all); (rename_i heq2; split at heq2 <;> cases heq2))

/-! ## Loop-over-range spec

Specialized to `loop` over `core.ops.range.Range Usize` (the Aeneas encoding
of Rust `for i in s..e` loops). -/

section loop_range_helpers

private abbrev ResultPS := PostShape.except Error (PostShape.except PUnit PostShape.pure)

private theorem triple_noThrow_elim {x : Result α} {Q : α → Assertion ResultPS}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ PostCond.noThrow Q ⦄) {v : α} (hv : x = ok v) :
    (Q v).down := by
  subst hv; simpa [Triple, WP.wp] using h

private theorem triple_noThrow_exists_ok {x : Result α} {Q : α → Assertion ResultPS}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ PostCond.noThrow Q ⦄) : ∃ v, x = ok v := by
  match x, h with
  | .ok v, _ => exact ⟨v, rfl⟩
  | .fail e, h => exact absurd h (by simp [Triple, WP.wp, PredTrans.apply])
  | .div, h => exact absurd h (by simp [Triple, WP.wp, PredTrans.apply])

private theorem triple_of_ok {x : Result α} {v : α} {P : α → Prop}
    (hx : x = ok v) (hp : P v) :
    (⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄) := by
  subst hx; simp [Triple, WP.wp, hp, PredTrans.apply]

private theorem usize_add_one_toNat (x : USize) (h : x.toNat + 1 < USize.size) :
    (USize.add x 1).toNat = x.toNat + 1 := by
  show (USize.add x 1).toBitVec.toNat = x.toBitVec.toNat + 1
  simp [USize.add, USize.size] at *
  exact Nat.mod_eq_of_lt h

end loop_range_helpers

set_option maxHeartbeats 2000000 in
theorem loop_range_spec {β : Type}
    (body : (core.ops.range.Range Usize × β) →
      Result (ControlFlow (core.ops.range.Range Usize × β) β))
    (init : β) (s e : Usize) (inv : Usize → β → Result Prop)
    (h_le : s.val ≤ e.val)
    (h_init : (inv s init).holds)
    (h_step : ∀ acc (i : Usize), s.val ≤ i.val → i.val ≤ e.val →
      (inv i acc).holds →
      ⦃ ⌜ True ⌝ ⦄
      body ({ start := i, «end» := e }, acc)
      ⦃ ⇓ r => match r with
        | .cont (iter', acc') =>
          ⌜ i.val < e.val ∧ iter'.«end» = e ∧ iter'.start.val = i.val + 1
            ∧ (inv iter'.start acc').holds ⌝
        | .done y => ⌜ (inv e y).holds ⌝ ⦄) :
    ⦃ ⌜ True ⌝ ⦄
    loop body ({ start := s, «end» := e }, init)
    ⦃ ⇓ r => ⌜ (inv e r).holds ⌝ ⦄ := by
  -- Generalize over the current iteration's `start` and induct on the number
  -- of remaining steps `n = e.val - start.val`.
  suffices gen : ∀ (n : Nat) (acc : β) (start : Usize),
    e.val - start.val = n →
    s.val ≤ start.val → start.val ≤ e.val →
    (inv start acc).holds →
    ⦃ ⌜ True ⌝ ⦄ loop body ({ start := start, «end» := e }, acc)
    ⦃ ⇓ r => ⌜ (inv e r).holds ⌝ ⦄ by
    exact gen _ init s rfl (Nat.le_refl _) h_le h_init
  intro n
  induction n with
  | zero =>
    intro acc start hn hs_le hse_le hinv
    have hs := h_step acc start hs_le hse_le hinv
    obtain ⟨r, hbody⟩ := triple_noThrow_exists_ok hs
    have hpost := triple_noThrow_elim hs hbody
    rw [loop.eq_def, hbody]
    match r with
    | .cont (iter', acc') =>
      simp at hpost; exact absurd hpost.1 (by omega)
    | .done y =>
      simp at hpost; exact triple_of_ok rfl hpost
  | succ n ih =>
    intro acc start hn hs_le hse_le hinv
    have hs := h_step acc start hs_le hse_le hinv
    obtain ⟨r, hbody⟩ := triple_noThrow_exists_ok hs
    have hpost := triple_noThrow_elim hs hbody
    rw [loop.eq_def, hbody]
    match r with
    | .done y =>
      simp at hpost; exact triple_of_ok rfl hpost
    | .cont (iter', acc') =>
      simp at hpost
      obtain ⟨hlt, hend, hstart, hinv'⟩ := hpost
      have hiter : iter' = { start := iter'.start, «end» := e } := by
        cases iter'; cases hend; rfl
      rw [hiter]
      exact ih acc' iter'.start
        (by rw [hstart]; omega) (by rw [hstart]; omega) (by rw [hstart]; omega) hinv'

/-! ## `for`-loop-with-invariant spec

The definition `Hax.forLoopWithInvariant` and the tactic `for_loop_with_invariant`
that rewrites a raw `loop _ _` into this form live in `Hax.Tactic.ForLoopWithInvariant`. -/

@[spec]
theorem forLoopWithInvariant_spec {β : Type}
    (body : Usize → β → Result β)
    (init : β) (s e : Usize) (inv : Usize → β → Result Prop)
    (h_le : s.val ≤ e.val)
    (h_init : (inv s init).holds)
    (h_step : ∀ acc (i : Usize), s.val ≤ i.val → i.val < e.val →
      (inv i acc).holds →
      ⦃ ⌜ True ⌝ ⦄
      body i acc
      ⦃ ⇓ r => ⌜ ∀ (i' : Usize), i'.val = i.val + 1 → (inv i' r).holds ⌝ ⦄) :
    ⦃ ⌜ True ⌝ ⦄
    Hax.forLoopWithInvariant core.Usize.Insts.CoreIterRangeStep inv body
      { start := s, «end» := e } init
    ⦃ ⇓ r => ⌜ (inv e r).holds ⌝ ⦄ := by
  unfold Hax.forLoopWithInvariant
  apply loop_range_spec _ init s e inv h_le h_init
  intro acc i hsi hie hinv
  unfold core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
    core.IteratorRange.next core.Usize.Insts.CoreIterRangeStep
  by_cases hlt : i.val < e.val
  · -- i < e: `next` yields `(some i, iter')` with `iter'.start.val = i.val + 1`,
    -- then `body i acc` yields the next accumulator.
    have hbody := h_step acc i hsi hlt hinv
    obtain ⟨r, hbody_eq⟩ := triple_noThrow_exists_ok hbody
    have hpost := triple_noThrow_elim hbody hbody_eq
    simp at hpost
    have hbnd : i.val + (1#usize).val ≤ Usize.max := by scalar_tac
    have hno_ovf := UScalar.overflowing_add_eq i (1#usize)
    have hi1_le : ¬ (i.val + (1#usize).val > UScalar.max .Usize) := by scalar_tac
    simp only [hi1_le, if_false] at hno_ovf
    obtain ⟨hsv, hovf⟩ := hno_ovf
    simp only [Triple, PredTrans.apply, wp, core.Usize.Insts.CoreCmpPartialOrdUsize,
      core.mkUPartialOrd, compare, compareOfLessAndEq, hlt, ↓reduceIte,
      core.Usize.Insts.CoreCloneClone.clone, core.Usize.Insts.CoreIterRangeStep.forward_checked,
      core.convert.TryFromUTInfallible.Blanket.try_from, core.convert.From.Blanket.from, bind_tc_ok,
      core.num.Usize.checked_add, core.num.Usize.overflowing_add,
      rust_primitives.arithmetic.overflowing_add_usize, bind_assoc, holds, ExceptConds.fst_false,
      ExceptConds.snd_false, SPred.entails_nil, SPred.down_pure, forall_const, true_and]
    generalize hov : UScalar.overflowing_add i (1#usize) = ov at *
    obtain ⟨i', overflowed⟩ := ov
    simp at hsv hovf
    subst hovf
    have hi'val' : i'.val = i.val + 1 := by simpa using hsv
    have hh : (inv i' r).holds := hpost i' hi'val'
    simp [Triple, WP.wp, Result.holds, PredTrans.apply, hbody_eq] at hh ⊢
    refine ⟨hi'val', ?_⟩
    rcases hires : inv i' r with _ | _ | _ <;> simp [hires] at hh ⊢; exact hh
  · -- i ≥ e: combined with `hie`, `i = e`. `next` yields `(none, _)`, body short-circuits.
    have hieq : i.val = e.val := Nat.le_antisymm hie (Nat.le_of_not_lt hlt)
    have hi_eq_e : i = e := UScalar.eq_imp _ _ hieq
    have hh : (inv e acc).holds := by rw [← hi_eq_e]; exact hinv
    simp [compare, compareOfLessAndEq, hi_eq_e,
          core.Usize.Insts.CoreCmpPartialOrdUsize, core.mkUPartialOrd,
          Triple, WP.wp, Result.holds] at hh ⊢
    exact hh

