import Chacha20.Extraction.Funs
import Chacha20.Extraction.Specs
import Hax
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do

set_option mvcgen.warning false
set_option hax_mvcgen.warnings false
set_option maxHeartbeats 1000000

namespace chacha20

-- Let `hax_mvcgen` step through the tuple destructuring produced by `index_mut`.
attribute [local spec] uncurry

/-- `chacha20_line` is panic-free: every state index uses a `BoundedUsize<0,15>`
which is in range for the length-16 state. -/
@[spec]
theorem chacha20_line_spec
    (a b d : hax_bounded_integers.hax__autogenerated_refinement__BoundedUsize.BoundedUsize
      0#usize 15#usize)
    (s : Std.U32) (m : Array Std.U32 16#usize) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20_line a b d s m
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold chacha20_line
  simp only [core.Array.Insts.CoreOpsIndexIndex.index,
    core.Array.Insts.CoreOpsIndexIndexMut.index_mut,
    hax_bounded_integers.Slice.Insts.CoreOpsIndexIndexBoundedUsizeT,
    hax_bounded_integers.Slice.Insts.CoreOpsIndexIndexMutBoundedUsizeT,
    core.array.Array.as_slice, rust_primitives.slice.array_as_slice,
    core.num.U32.wrapping_add, core.num.U32.rotate_left,
    rust_primitives.arithmetic.wrapping_add_u32,
    rust_primitives.arithmetic.rotate_left_u32]
  hax_mvcgen
  all_goals
    simp only [Array.length_to_slice]
    have ha := a.hhi; have hb := b.hhi; have hd := d.hhi
    scalar_tac

/-- `into_checked` succeeds whenever the value is within `[lo, hi]`. -/
@[spec]
theorem into_checked_spec (lo hi x : Std.Usize)
    (h : lo.val ≤ x.val ∧ x.val ≤ hi.val) :
    ⦃ ⌜ True ⌝ ⦄
    hax_bounded_integers.Usize.Insts.Hax_libRefineAsBoundedUsize.into_checked lo hi x
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold hax_bounded_integers.Usize.Insts.Hax_libRefineAsBoundedUsize.into_checked
  rw [dif_pos h]
  hax_mvcgen

/-- `chacha20_quarter_round` is panic-free (four panic-free `chacha20_line`s). -/
@[spec]
theorem chacha20_quarter_round_spec
    (a b c d : hax_bounded_integers.hax__autogenerated_refinement__BoundedUsize.BoundedUsize
      0#usize 15#usize)
    (state : Array Std.U32 16#usize) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20_quarter_round a b c d state
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold chacha20_quarter_round
  hax_mvcgen

/-- `chacha20_double_round` is panic-free. -/
@[spec]
theorem chacha20_double_round_spec (state : Array Std.U32 16#usize) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20_double_round state
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold chacha20_double_round
  hax_mvcgen

end chacha20
