import Chacha20.Extraction.Funs
import Chacha20.Extraction.Specs
import Chacha20.Proofs.Missing
import Hax
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do

set_option mvcgen.warning false
set_option hax_mvcgen.warnings false
set_option maxHeartbeats 1000000

namespace chacha20

-- Let `hax_mvcgen` step through the tuple destructuring produced by `index_mut`.
attribute [local spec] uncurry

/-- `chacha20_line` is panic-free: every state index uses a `BoundedUsize<0,15>`
which is in range for the length-16 state. -/
@[spec]
theorem chacha20_line_spec
    (a b d : hax_bounded_integers.hax__autogenerated_refinement__BoundedUsize.BoundedUsize
      0#usize 15#usize)
    (s : Std.U32) (m : Array Std.U32 16#usize) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20_line a b d s m
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold chacha20_line
  simp only [core.Array.Insts.CoreOpsIndexIndex.index,
    core.Array.Insts.CoreOpsIndexIndexMut.index_mut,
    hax_bounded_integers.Slice.Insts.CoreOpsIndexIndexBoundedUsizeT,
    hax_bounded_integers.Slice.Insts.CoreOpsIndexIndexMutBoundedUsizeT,
    core.array.Array.as_slice, rust_primitives.slice.array_as_slice,
    core.num.U32.wrapping_add, core.num.U32.rotate_left,
    rust_primitives.arithmetic.wrapping_add_u32,
    rust_primitives.arithmetic.rotate_left_u32]
  hax_mvcgen
  all_goals
    simp only [Array.length_to_slice]
    have ha := a.hhi; have hb := b.hhi; have hd := d.hhi
    scalar_tac

/-- `into_checked` succeeds whenever the value is within `[lo, hi]`. -/
@[spec]
theorem into_checked_spec (lo hi x : Std.Usize)
    (h : lo.val ≤ x.val ∧ x.val ≤ hi.val) :
    ⦃ ⌜ True ⌝ ⦄
    hax_bounded_integers.Usize.Insts.Hax_libRefineAsBoundedUsize.into_checked lo hi x
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold hax_bounded_integers.Usize.Insts.Hax_libRefineAsBoundedUsize.into_checked
  rw [dif_pos h]
  hax_mvcgen

/-- `chacha20_quarter_round` is panic-free (four panic-free `chacha20_line`s). -/
@[spec]
theorem chacha20_quarter_round_spec
    (a b c d : hax_bounded_integers.hax__autogenerated_refinement__BoundedUsize.BoundedUsize
      0#usize 15#usize)
    (state : Array Std.U32 16#usize) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20_quarter_round a b c d state
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold chacha20_quarter_round
  hax_mvcgen

/-- `chacha20_double_round` is panic-free. -/
@[spec]
theorem chacha20_double_round_spec (state : Array Std.U32 16#usize) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20_double_round state
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold chacha20_double_round
  hax_mvcgen

/-- `xor_state` is panic-free: a `0..16` loop over the length-16 state. -/
@[spec]
theorem xor_state_spec (state other : Array Std.U32 16#usize) :
    ⦃ ⌜ True ⌝ ⦄
    hacspec_helper.xor_state state other
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold hacspec_helper.xor_state hacspec_helper.xor_state_loop
    hacspec_helper.xor_state_loop.body
  for_loop_with_invariant fun _ _ => pure True
  mvcgen
  all_goals first
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- `add_state` is panic-free: a `0..16` loop over the length-16 state. -/
@[spec]
theorem add_state_spec (state other : Array Std.U32 16#usize) :
    ⦃ ⌜ True ⌝ ⦄
    hacspec_helper.add_state state other
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold hacspec_helper.add_state hacspec_helper.add_state_loop
    hacspec_helper.add_state_loop.body
  simp only [core.num.U32.wrapping_add, rust_primitives.arithmetic.wrapping_add_u32]
  for_loop_with_invariant fun _ _ => pure True
  mvcgen
  all_goals first
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- Inner loop of `u32s_to_le_bytes`: writes bytes `i*4 .. i*4+4` of the output.
Panic-free provided `i < 16` (so `i*4+j < 64`). -/
@[spec]
theorem u32s_to_le_bytes_inner_spec
    (out : Array Std.U8 64#usize) (i : Std.Usize) (tmp : Array Std.U8 4#usize)
    (hi : i.val < 16) :
    ⦃ ⌜ True ⌝ ⦄
    hacspec_helper.u32s_to_le_bytes_loop0_loop0 { start := 0#usize, «end» := 4#usize } out i tmp
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold hacspec_helper.u32s_to_le_bytes_loop0_loop0
    hacspec_helper.u32s_to_le_bytes_loop0_loop0.body
  for_loop_with_invariant fun _ _ => pure True
  hax_mvcgen
  all_goals first
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- Outer loop of `u32s_to_le_bytes` over `0..e` with `e ≤ 16`: reads `state[i]`
(`i < 16`) and runs the inner loop (panic-free since `i < 16`). -/
@[spec]
theorem u32s_to_le_bytes_loop0_spec
    (state : Array Std.U32 16#usize) (out : Array Std.U8 64#usize) (e : Std.Usize)
    (he : e.val ≤ 16) :
    ⦃ ⌜ True ⌝ ⦄
    hacspec_helper.u32s_to_le_bytes_loop0 { start := 0#usize, «end» := e } state out
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold hacspec_helper.u32s_to_le_bytes_loop0 hacspec_helper.u32s_to_le_bytes_loop0.body
  simp only [core.num.U32.to_le_bytes, rust_primitives.arithmetic.to_le_bytes_u32]
  for_loop_with_invariant fun _ _ => pure True
  mstart
  mvcgen
  all_goals first
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- `u32s_to_le_bytes` is panic-free: the outer loop runs over `0..16`. -/
@[spec]
theorem u32s_to_le_bytes_spec (state : Array Std.U32 16#usize) :
    ⦃ ⌜ True ⌝ ⦄
    hacspec_helper.u32s_to_le_bytes state
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold hacspec_helper.u32s_to_le_bytes
  simp only [core.slice.Slice.len]
  hax_mvcgen
  all_goals first
    | (simp only [Slice.len, Array.length_to_slice]; scalar_tac)
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- Loop of `update_array` over `0..e`: writes `array[i] := val[i]`. Panic-free
when `e ≤ val.length` (source bound) and `val.length ≤ 64` (dest bound). -/
@[spec]
theorem update_array_loop_spec
    (array : Array Std.U8 64#usize) (val : Slice Std.U8) (e : Std.Usize)
    (hle : e.val ≤ val.length) (h64 : val.length ≤ 64) :
    ⦃ ⌜ True ⌝ ⦄
    hacspec_helper.update_array_loop { start := 0#usize, «end» := e } array val
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold hacspec_helper.update_array_loop hacspec_helper.update_array_loop.body
  for_loop_with_invariant fun _ _ => pure True
  mstart
  mvcgen
  all_goals first
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- `update_array` is panic-free given `val.length ≤ 64`. -/
@[spec]
theorem update_array_spec
    (array : Array Std.U8 64#usize) (val : Slice Std.U8) (hpre : val.length ≤ 64) :
    ⦃ ⌜ True ⌝ ⦄
    hacspec_helper.update_array array val
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold hacspec_helper.update_array
  simp only [core.slice.Slice.len]
  hax_mvcgen
  all_goals first
    | (simp only [Slice.len]; scalar_tac)
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- Loop of `to_le_u32s_3` over `0..e` with `e ≤ 3` and `4*3 ≤ bytes.length`:
each iteration reads `bytes[4i .. 4i+4]` (in range) and writes `out[i]`
(`i < 3`). Panic-free. -/
@[spec]
theorem to_le_u32s_3_loop_spec
    (bytes : Slice Std.U8) (out : Array Std.U32 3#usize) (e : Std.Usize)
    (he : e.val ≤ 3) (hb : 12 ≤ bytes.length) :
    ⦃ ⌜ True ⌝ ⦄
    hacspec_helper.to_le_u32s_3_loop { start := 0#usize, «end» := e } bytes out
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold hacspec_helper.to_le_u32s_3_loop hacspec_helper.to_le_u32s_3_loop.body
  simp only [core.num.U32.from_le_bytes, rust_primitives.arithmetic.from_le_bytes_u32]
  for_loop_with_invariant fun _ _ => pure True
  mstart
  mvcgen
  all_goals first
    | scalar_tac
    | assumption
    | (intro h; first | exact h | scalar_tac | simp_all [Result.holds])
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- `to_le_u32s_3` is panic-free given `12 ≤ bytes.length` (its `bytes.len() >= 4*3`
precondition). -/
@[spec]
theorem to_le_u32s_3_spec (bytes : Slice Std.U8) (hb : 12 ≤ bytes.length) :
    ⦃ ⌜ True ⌝ ⦄
    hacspec_helper.to_le_u32s_3 bytes
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold hacspec_helper.to_le_u32s_3
  hax_mvcgen
  all_goals first
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- Loop of `to_le_u32s_8` over `0..e` with `e ≤ 8` and `4*8 ≤ bytes.length`. -/
@[spec]
theorem to_le_u32s_8_loop_spec
    (bytes : Slice Std.U8) (out : Array Std.U32 8#usize) (e : Std.Usize)
    (he : e.val ≤ 8) (hb : 32 ≤ bytes.length) :
    ⦃ ⌜ True ⌝ ⦄
    hacspec_helper.to_le_u32s_8_loop { start := 0#usize, «end» := e } bytes out
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold hacspec_helper.to_le_u32s_8_loop hacspec_helper.to_le_u32s_8_loop.body
  simp only [core.num.U32.from_le_bytes, rust_primitives.arithmetic.from_le_bytes_u32]
  for_loop_with_invariant fun _ _ => pure True
  mstart
  mvcgen
  all_goals first
    | scalar_tac
    | assumption
    | (intro h; first | exact h | scalar_tac | simp_all [Result.holds])
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- `to_le_u32s_8` is panic-free given `32 ≤ bytes.length`. -/
@[spec]
theorem to_le_u32s_8_spec (bytes : Slice Std.U8) (hb : 32 ≤ bytes.length) :
    ⦃ ⌜ True ⌝ ⦄
    hacspec_helper.to_le_u32s_8 bytes
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold hacspec_helper.to_le_u32s_8
  hax_mvcgen
  all_goals first
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- Loop of `to_le_u32s_16` over `0..e` with `e ≤ 16` and `4*16 ≤ bytes.length`. -/
@[spec]
theorem to_le_u32s_16_loop_spec
    (bytes : Slice Std.U8) (out : Array Std.U32 16#usize) (e : Std.Usize)
    (he : e.val ≤ 16) (hb : 64 ≤ bytes.length) :
    ⦃ ⌜ True ⌝ ⦄
    hacspec_helper.to_le_u32s_16_loop { start := 0#usize, «end» := e } bytes out
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold hacspec_helper.to_le_u32s_16_loop hacspec_helper.to_le_u32s_16_loop.body
  simp only [core.num.U32.from_le_bytes, rust_primitives.arithmetic.from_le_bytes_u32]
  for_loop_with_invariant fun _ _ => pure True
  mstart
  mvcgen
  all_goals first
    | scalar_tac
    | assumption
    | (intro h; first | exact h | scalar_tac | simp_all [Result.holds])
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- `to_le_u32s_16` is panic-free given `64 ≤ bytes.length`. -/
@[spec]
theorem to_le_u32s_16_spec (bytes : Slice Std.U8) (hb : 64 ≤ bytes.length) :
    ⦃ ⌜ True ⌝ ⦄
    hacspec_helper.to_le_u32s_16 bytes
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold hacspec_helper.to_le_u32s_16
  hax_mvcgen
  all_goals first
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- `chacha20_init` is panic-free: `to_le_u32s_8`/`to_le_u32s_3` on the length-32
key / length-12 iv, then in-range reads (`< 8` / `< 3`) into a length-16 state. -/
@[spec]
theorem chacha20_init_spec
    (key : Array Std.U8 32#usize) (iv : Array Std.U8 12#usize) (ctr : Std.U32) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20_init key iv ctr
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold chacha20_init
  hax_mvcgen
  all_goals first
    | (simp only [Slice.len, Array.length_to_slice]; scalar_tac)
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- `chacha20_rounds` is panic-free: 10 iterations of the panic-free
`chacha20_double_round` over an `i32` range `0..10`. -/
@[spec]
theorem chacha20_rounds_spec (state : Array Std.U32 16#usize) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20_rounds state
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold chacha20_rounds chacha20_rounds_loop chacha20_rounds_loop.body
  for_loop_with_invariant fun _ _ => pure True
  mstart
  mvcgen
  all_goals first
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- `chacha20_core` is panic-free: in-range read/write at index 12 of the
length-16 state, then `chacha20_rounds` and `add_state`. -/
@[spec]
theorem chacha20_core_spec (ctr : Std.U32) (st0 : Array Std.U32 16#usize) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20_core ctr st0
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold chacha20_core
  simp only [core.num.U32.wrapping_add, rust_primitives.arithmetic.wrapping_add_u32]
  hax_mvcgen
  all_goals first
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- `chacha20_key_block` is panic-free: `chacha20_core` then `u32s_to_le_bytes`. -/
@[spec]
theorem chacha20_key_block_spec (state : Array Std.U32 16#usize) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20_key_block state
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold chacha20_key_block
  hax_mvcgen
  all_goals first
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- `chacha20_key_block0` is panic-free: `chacha20_init` then `chacha20_key_block`. -/
@[spec]
theorem chacha20_key_block0_spec
    (key : Array Std.U8 32#usize) (iv : Array Std.U8 12#usize) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20_key_block0 key iv
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold chacha20_key_block0
  hax_mvcgen
  all_goals first
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- `chacha20_encrypt_block` is panic-free: `chacha20_core`, `to_le_u32s_16` on the
length-64 block, `xor_state`, `u32s_to_le_bytes`. -/
@[spec]
theorem chacha20_encrypt_block_spec
    (st0 : Array Std.U32 16#usize) (ctr : Std.U32) (plain : Array Std.U8 64#usize) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20_encrypt_block st0 ctr plain
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold chacha20_encrypt_block
  hax_mvcgen
  all_goals first
    | (simp only [Slice.len, Array.length_to_slice]; scalar_tac)
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- `chacha20_encrypt_last` is panic-free given `0 < plain.length ≤ 64`:
`update_array` (needs `≤ 64`), `chacha20_encrypt_block`, then `b[0..plain.len]`
(needs `0 < plain.len ≤ 64`) collected into a `Vec`. -/
@[spec]
theorem chacha20_encrypt_last_spec
    (st0 : Array Std.U32 16#usize) (ctr : Std.U32) (plain : Slice Std.U8)
    (hlo : 0 < plain.length) (hhi : plain.length ≤ 64) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20_encrypt_last st0 ctr plain
    ⦃ ⇓ r => ⌜ Slice.length r ≤ plain.length ⌝ ⦄ := by
  unfold chacha20_encrypt_last
  simp only [core.Array.Insts.CoreOpsIndexIndex.index, core.array.Array.as_slice,
    rust_primitives.slice.array_as_slice, alloc.slice.Slice.to_vec,
    CoreModels.alloc.slice.Dummy.to_vec, core.slice.Slice.len,
    rust_primitives.sequence.seq_empty, rust_primitives.sequence.seq_extend]
  hax_mvcgen
  all_goals first
    | (apply absurd _ ‹_›
       simp only [Slice.new, List.nil_append, List.length_append, List.length_nil]
       scalar_tac)
    | (simp only [Slice.new, List.nil_append, List.length_append, List.length_nil,
         Slice.len, Slice.length]
       scalar_tac)
    | (simp only [Slice.len, Array.length_to_slice, Array.length_repeat]; scalar_tac)
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

/-- Loop of `chacha20_update` over `0..e` with `64*e ≤ m.length`. Each iteration
appends a 64-byte encrypted block to `blocks_out`; the invariant
`blocks_out.length ≤ i*64` keeps the `Vec` within `Usize.max`. -/
@[spec]
theorem chacha20_update_loop_spec
    (st0 : Array Std.U32 16#usize) (m : Slice Std.U8) (e : Std.Usize)
    (blocks_out : alloc.vec.Vec Std.U8)
    (hnb : 64 * e.val ≤ m.length) (hinit : blocks_out.length = 0) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20_update_loop { start := 0#usize, «end» := e } st0 m blocks_out
    ⦃ ⇓ r => ⌜ Slice.length r ≤ e.val * 64 ⌝ ⦄ := by
  unfold chacha20_update_loop chacha20_update_loop.body
  simp only [alloc.vec.Vec.len, rust_primitives.sequence.seq_len,
    alloc.vec.Vec.extend_from_slice, rust_primitives.sequence.seq_extend,
    hax_lib.prop.Prop.Insts.CoreConvertFromBool.from, hax_lib.assume]
  for_loop_with_invariant fun (i : Std.Usize) (bo : alloc.vec.Vec Std.U8) =>
    pure (bo.length ≤ i.val * 64)
  mstart
  mvcgen
  all_goals first
    | scalar_tac
    | (intro h; exact h)                                    -- vc8: `∃..` → `∃..`
    | (intro h; scalar_tac)                                 -- vc9/10/11: bound side-conditions
    | (intro i' hi'                                          -- vc6: invariant preservation
       simp [Result.holds, Triple, WP.wp, PredTrans.apply, List.length_append,
         Array.length_to_slice, Slice.length] at * <;> scalar_tac)
    | (simp [Result.holds, Triple, WP.wp, PredTrans.apply, List.length_append,
         Array.length_to_slice, Slice.length] at * <;> scalar_tac)  -- vc7

/-- `chacha20_update` is panic-free: `num_blocks = m.len/64` full blocks (the loop),
then a partial last block when `m.len % 64 ≠ 0`. The `Vec` stays within `Usize.max`
because the accumulated length never exceeds `m.len`. -/
@[spec]
theorem chacha20_update_spec (st0 : Array Std.U32 16#usize) (m : Slice Std.U8) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20_update st0 m
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold chacha20_update
  simp only [alloc.vec.Vec.new, rust_primitives.sequence.seq_empty,
    core.slice.Slice.len, alloc.vec.Vec.len, rust_primitives.sequence.seq_len,
    hax_lib.prop.Prop.Insts.CoreConvertFromBool.from, hax_lib.assume,
    alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref, alloc.vec.Vec.as_slice,
    rust_primitives.sequence.seq_to_slice,
    alloc.vec.Vec.extend_from_slice, rust_primitives.sequence.seq_extend]
  hax_mvcgen
  all_goals (try simp only [bne_iff_ne, ne_eq] at *)
  all_goals first
    | scalar_tac
    | (intro h; scalar_tac)
    | (simp [Result.holds, Triple, WP.wp, PredTrans.apply, List.length_append,
        Array.length_to_slice, Slice.length] at * <;> scalar_tac)

/-- `chacha20` is panic-free: `chacha20_init` then `chacha20_update`. -/
@[spec]
theorem chacha20_spec
    (m : Slice Std.U8) (key : Array Std.U8 32#usize) (iv : Array Std.U8 12#usize)
    (ctr : Std.U32) :
    ⦃ ⌜ True ⌝ ⦄
    chacha20 m key iv ctr
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold chacha20
  hax_mvcgen
  all_goals first
    | scalar_tac
    | (intros; simp [Result.holds])
    | simp [Result.holds]

end chacha20
